### ISSUE TITLE
error looking up IP during taildrop send

### ISSUE THREAD

**Issue by jstebbins** [bahorn/nautilus-taildrop#3]
The script uses 'HostName' from 'tailscale status --json'. The HostName is not necessarily the name that can be resolved with DNS. Script should use 'DNSName' which is guaranteed to resolve and is fully qualified.

**Comment by jstebbins** [comment]
And I forgot to say thank you very much for this wonderful little tool :grinning:

**Comment by bahorn** [comment]
Thanks for the report, just merged a fix in https://github.com/bahorn/nautilus-taildrop/commit/1f2d3b2e848a2631b3d886d2a86328842ff3d75d
